-- ============================================
-- IDENTITY Counter Restart
-- GENERATED BY DEFAULT AS IDENTITY columns need restart
-- after explicit ID insertion via CSV seed data
-- ============================================

ALTER TABLE INV_WAREHOUSES ALTER COLUMN WAREHOUSE_ID RESTART WITH 11;
ALTER TABLE SAL_SALES_ORDERS ALTER COLUMN ID RESTART WITH 6;
ALTER TABLE SAL_SALES_ORDER_ITEMS ALTER COLUMN ID RESTART WITH 10;

COMMIT;
